# Copyright 2022 Thoughtworks, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

###############################################################################################
# This file is autogenerated by the repository at https://github.com/gocd/gocd.
# Please file any issues or PRs at https://github.com/gocd/gocd
###############################################################################################

FROM curlimages/curl:latest as gocd-server-unzip
USER root
ARG UID=1000
RUN curl --fail --location --silent --show-error "https://download.gocd.org/binaries/22.3.0-15301/generic/go-server-22.3.0-15301.zip" > /tmp/go-server-22.3.0-15301.zip && \
    unzip /tmp/go-server-22.3.0-15301.zip -d / && \
    mkdir -p /go-server/wrapper /go-server/bin && \
    mv /go-server-22.3.0/LICENSE /go-server/LICENSE && \
    mv /go-server-22.3.0/bin/go-server /go-server/bin/go-server && \
    mv /go-server-22.3.0/lib /go-server/lib && \
    mv /go-server-22.3.0/logs /go-server/logs && \
    mv /go-server-22.3.0/run /go-server/run && \
    mv /go-server-22.3.0/wrapper-config /go-server/wrapper-config && \
    mv /go-server-22.3.0/wrapper/wrapper-linux* /go-server/wrapper/ && \
    mv /go-server-22.3.0/wrapper/libwrapper-linux* /go-server/wrapper/ && \
    mv /go-server-22.3.0/wrapper/wrapper.jar /go-server/wrapper/ && \
    chown -R ${UID}:0 /go-server && chmod -R g=u /go-server

FROM quay.io/centos/centos:stream9

LABEL gocd.version="22.3.0" \
  description="GoCD server based on quay.io/centos/centos:stream9" \
  maintainer="GoCD Team <go-cd-dev@googlegroups.com>" \
  url="https://www.gocd.org" \
  gocd.full.version="22.3.0-15301" \
  gocd.git.sha="9d23ed19a9ea46eaf7f18bd16671ae0569871f53"

# the ports that GoCD server runs on
EXPOSE 8153

ADD https://github.com/krallin/tini/releases/download/v0.19.0/tini-static-amd64 /usr/local/sbin/tini

# force encoding
ENV LANG=en_US.UTF-8 LANGUAGE=en_US:en LC_ALL=en_US.UTF-8
ENV GO_JAVA_HOME="/gocd-jre"

ARG UID=1000

RUN \
# add mode and permissions for files we added above
  chmod 0755 /usr/local/sbin/tini && \
  chown root:root /usr/local/sbin/tini && \
# add our user and group first to make sure their IDs get assigned consistently,
# regardless of whatever dependencies get added
# add user to root group for GoCD to work on openshift
  useradd -l -u ${UID} -g root -d /home/go -m go && \
  dnf install --assumeyes glibc-langpack-en epel-release && \
  dnf update -y && \
  dnf upgrade -y && \
  dnf install -y git mercurial subversion openssh-clients bash unzip procps procps-ng coreutils-single curl-minimal && \
  dnf clean all && \
  rm -rf /var/cache/dnf && \
  curl --fail --location --silent --show-error 'https://github.com/adoptium/temurin17-binaries/releases/download/jdk-17.0.5%2B8/OpenJDK17U-jre_x64_linux_hotspot_17.0.5_8.tar.gz' --output /tmp/jre.tar.gz && \
  mkdir -p /gocd-jre && \
  tar -xf /tmp/jre.tar.gz -C /gocd-jre --strip 1 && \
  rm -rf /tmp/jre.tar.gz && \
  mkdir -p /go-server /docker-entrypoint.d /go-working-dir /godata

ADD docker-entrypoint.sh /

COPY --from=gocd-server-unzip /go-server /go-server
# ensure that logs are printed to console output
COPY --chown=go:root logback-include.xml /go-server/config/logback-include.xml
COPY --chown=go:root install-gocd-plugins git-clone-config /usr/local/sbin/

RUN chown -R go:root /docker-entrypoint.d /go-working-dir /godata /docker-entrypoint.sh && \
    chmod -R g=u /docker-entrypoint.d /go-working-dir /godata /docker-entrypoint.sh

ENTRYPOINT ["/docker-entrypoint.sh"]

USER go
