# Copyright 2023 Thoughtworks, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

###############################################################################################
# This file is autogenerated by the repository at https://github.com/gocd/gocd.
# Please file any issues or PRs at https://github.com/gocd/gocd
###############################################################################################

FROM curlimages/curl:latest as gocd-server-unzip
USER root
ARG TARGETARCH
ARG UID=1000
RUN curl --fail --location --silent --show-error "https://download.gocd.org/binaries/23.5.0-18179/generic/go-server-23.5.0-18179.zip" > /tmp/go-server-23.5.0-18179.zip && \
    unzip -q /tmp/go-server-23.5.0-18179.zip -d / && \
    mkdir -p /go-server/wrapper /go-server/bin && \
    mv -v /go-server-23.5.0/LICENSE /go-server/LICENSE && \
    mv -v /go-server-23.5.0/bin/go-server /go-server/bin/go-server && \
    mv -v /go-server-23.5.0/lib /go-server/lib && \
    mv -v /go-server-23.5.0/logs /go-server/logs && \
    mv -v /go-server-23.5.0/run /go-server/run && \
    mv -v /go-server-23.5.0/wrapper-config /go-server/wrapper-config && \
    WRAPPERARCH=$(if [ $TARGETARCH == amd64 ]; then echo x86-64; elif [ $TARGETARCH == arm64 ]; then echo arm-64; else echo $TARGETARCH is unknown!; exit 1; fi) && \
    mv -v /go-server-23.5.0/wrapper/wrapper-linux-$WRAPPERARCH* /go-server/wrapper/ && \
    mv -v /go-server-23.5.0/wrapper/libwrapper-linux-$WRAPPERARCH* /go-server/wrapper/ && \
    mv -v /go-server-23.5.0/wrapper/wrapper.jar /go-server/wrapper/ && \
    chown -R ${UID}:0 /go-server && chmod -R g=u /go-server

FROM quay.io/centos/centos:stream9-minimal
ARG TARGETARCH

LABEL gocd.version="23.5.0" \
  description="GoCD server based on quay.io/centos/centos:stream9-minimal" \
  maintainer="GoCD Team <go-cd-dev@googlegroups.com>" \
  url="https://www.gocd.org" \
  gocd.full.version="23.5.0-18179" \
  gocd.git.sha="7702b283accd1f90f014f0087aa2e9bd8baf4a97"

# the ports that GoCD server runs on
EXPOSE 8153

ADD https://github.com/krallin/tini/releases/download/v0.19.0/tini-static-${TARGETARCH} /usr/local/sbin/tini

# force encoding
ENV LANG=en_US.UTF-8 LANGUAGE=en_US:en LC_ALL=en_US.UTF-8
ENV GO_JAVA_HOME="/gocd-jre"

ARG UID=1000

RUN \
# add mode and permissions for files we added above
  chmod 0755 /usr/local/sbin/tini && \
  chown root:root /usr/local/sbin/tini && \
  echo 'fastestmirror=1' >> /etc/dnf/dnf.conf && \
  echo 'install_weak_deps=False' >> /etc/dnf/dnf.conf && \
  microdnf upgrade -y && \
  microdnf install -y shadow-utils && \
# add our user and group first to make sure their IDs get assigned consistently, regardless of whatever dependencies get added
  useradd -l -u ${UID} -g root -d /home/go -m go && \
  microdnf install -y tar tzdata epel-release epel-next-release && \
  microdnf install -y git-core openssh-clients bash unzip procps-ng coreutils-single glibc-langpack-en  curl-minimal && \
  microdnf clean all && \
  rm -rf /var/cache/yum /var/cache/dnf && \
  curl --fail --location --silent --show-error "https://github.com/adoptium/temurin17-binaries/releases/download/jdk-17.0.9%2B9/OpenJDK17U-jre_$(uname -m | sed -e s/86_//g)_linux_hotspot_17.0.9_9.tar.gz" --output /tmp/jre.tar.gz && \
  mkdir -p /gocd-jre && \
  tar -xf /tmp/jre.tar.gz -C /gocd-jre --strip 1 && \
  rm -rf /tmp/jre.tar.gz && \
  mkdir -p /go-server /docker-entrypoint.d /go-working-dir /godata

ADD docker-entrypoint.sh /

COPY --from=gocd-server-unzip /go-server /go-server
# ensure that logs are printed to console output
COPY --chown=go:root logback-include.xml /go-server/config/logback-include.xml
COPY --chown=go:root install-gocd-plugins git-clone-config /usr/local/sbin/

RUN chown -R go:root /docker-entrypoint.d /go-working-dir /godata /docker-entrypoint.sh && \
    chmod -R g=u /docker-entrypoint.d /go-working-dir /godata /docker-entrypoint.sh

ENTRYPOINT ["/docker-entrypoint.sh"]

USER go
